ADMIN_PASSWORD = "gsa007"
DATABASE_URL = "postgresql://postgres:*vh2Q&vRKT6d!2c@db.fhLbmtvhsdgcajyfpYl.supabase.co:5432/postgres"

SENDER_EMAIL = "ezondiza@gmail.com"
SENDER_PASSWORD = "ecxo sqob ifcl ympu"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
